create table if not exists public.products (
    id bigint generated by default as identity primary key,

    part_number varchar(100) not null unique,

    brand varchar(100),
    model varchar(100),
    description text,

    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create index if not exists idx_products_part_number
    on public.products(part_number);

