"""
schema.py -- Target Schema & Column Classification for Anvaya Enrichment Pipeline

WHAT: Defines every column in the expected output delivery format and
      categorizes it by how the pipeline should populate it.

WHY:  This is the single source of truth for "what does the pipeline
      need to produce?". Every module checks here to know which columns
      it owns, and evaluation checks here to know what to score.

HOW:  Each column is assigned to exactly one category:

      PASSTHROUGH  - Copied from raw input unchanged.
      CLEAN        - Copied from raw input, then cleaned (placeholder
                     removal, whitespace trimming, etc.).
      DETERMINISTIC - Generated by rule-based logic from raw columns
                     (string parsing, formatting templates). No AI needed.
      AI_ENRICHMENT - Requires semantic understanding (NLP, embeddings,
                     LLM generation). Built in later phases.
      EXTERNAL_DATA - Cannot be derived from the 6 raw columns at all.
                     Requires external reference files, web lookups,
                     or manual entry.

NOTE: Some columns are listed under DETERMINISTIC with a caveat that
      they produce partial/approximate output without external data.
      The pipeline should still attempt them, and flag low-confidence
      results for human review.
"""


# =========================================================================
# RAW INPUT COLUMNS (for reference)
# =========================================================================
RAW_INPUT_COLUMNS = [
    "Mfg_Part_Num",
    "Part_Desc",
    "E1_Brand",
    "Unilog_Brand",
    "DIB_Brand",
    "Part_Manuf",
]


# =========================================================================
# PLACEHOLDER VALUES -- these mean "empty/null", never real data
# =========================================================================
BRAND_PLACEHOLDERS = frozenset([
    "-- Unbranded --",
    "-- No Unilog Brand --",
    "-- No DIB Brand --",
])


# =========================================================================
# COLUMN CATEGORIES
# =========================================================================

# --- PASSTHROUGH: copied from raw input, no transformation ---
PASSTHROUGH_COLUMNS = [
    "Mfg_Part_Num",        # primary key
    "Part_Desc",           # raw description preserved as-is
]

# --- CLEAN: copied from raw, then cleaned ---
# These columns exist in raw input but may contain placeholder values
# that need to be replaced with empty/null.
CLEAN_COLUMNS = [
    "E1_Brand",            # replace placeholders with empty
    "Unilog_Brand",        # replace placeholders with empty
    "DIB_Brand",           # replace placeholders with empty
    "Part_Manuf",          # trim whitespace, kept as-is otherwise
]

# --- DETERMINISTIC: generated by rule-based logic from raw columns ---
# These can be built NOW with string parsing / templates.
DETERMINISTIC_COLUMNS = [
    # Identity -- extractable from Mfg_Part_Num / Part_Manuf
    "MANUFACTURER_PART_NUMBER",   # usually == Mfg_Part_Num
    # Note: MANUFACTURER_NAME is NOT simply Part_Manuf name portion.
    #   Example: Part_Manuf="Appliance Dealers Cooperative (APPDE)"
    #   but MANUFACTURER_NAME="Rheem Manufacturing" (the actual maker).
    #   For now, we extract the distributor name as a best-guess and
    #   flag it for human review. Accurate resolution needs the brand
    #   master list.

    # Descriptions -- templated from Part_Desc parsing
    "Product Name",        # short product type extracted from Part_Desc
                           # e.g. "PDSH4816AF Dishwasher SS" -> "Dishwasher"
    "INVOICE_DESC",        # ALL-CAPS abbreviated spec string
]

# --- AI_ENRICHMENT: requires NLP / semantic understanding ---
# Built in Phase 2 after deterministic slice is working.
AI_ENRICHMENT_COLUMNS = [
    # Descriptions that need semantic generation
    "MOBILE_DESC",         # manufacturer + brand + product + series + part#
    "SHORT_DESC",          # brand + series + part# + key specs (~150 chars)
    "LONG_DESC1",          # detailed spec string with all attribute values
    "RETAIL_DESC",         # customer-facing summary
    "MARKETING_DESCRIPTION",  # longer marketing copy

    # Features -- need AI to extract key selling points
    *[f"ITEM_FEATURES_{i}" for i in range(1, 21)],

    # Classification -- needs taxonomy + semantic matching
    "Dept",                # top-level category
    "Class",               # mid-level category
    "Fine",                # fine-grained category
    "Classpath",           # full taxonomy path (Dept > Class > Fine)
]

# --- EXTERNAL_DATA: cannot be derived from raw columns alone ---
# Requires reference files, web lookups, or manual entry.
EXTERNAL_DATA_COLUMNS = [
    # Identity
    "PART_NUMBER",             # system-assigned internal number
    "SKU - MY_PART_NUMBER",    # internal SKU
    "ALTERNATE_PART_NUMBER",   # variant part numbers
    "MANUFACTURER_NAME",       # actual manufacturer (not distributor!)
    "BRAND_NAME",              # resolved brand (needs brand master list)
    "TRADE_NAME",              # registered trademark name

    # Structured attributes (label/value/UOM triplets x 50)
    # Labels must come from controlled LOV; values need product specs;
    # UOMs need the UOM standards file.
    *[f"ATTRIBUTE_LABEL {i}" for i in range(1, 51)],
    *[f"ATTRIBUTE_VALUE {i}" for i in range(1, 51)],
    *[f"ATTRIBUTE_UOM {i}" for i in range(1, 51)],

    # Product extras
    "With",                    # "With [key feature]"
    "Standard/Approvals",      # certifications (pipe-delimited)
    "Prop 65",                 # California Prop 65 warning
    "Application",             # use-case text
    "Includes",                # box contents

    # Identifiers
    "UPC",
    "EAN",
    "GTIN",
    "UNSPSC",

    # Pricing
    "List Price",
    "Selling Qty",
    "Selling UOM",

    # Dimensions
    "LENGTH",  "LENGTH_UOM",
    "HEIGHT",  "HEIGHT_UOM",
    "WIDTH",   "WIDTH_UOM",
    "WEIGHT",  "WEIGHT_UOM",
    "VOLUME",  "VOLUME_UOM",
    "Standard Packaging Information",

    # Media
    "Product Image",
    "Alternate Image 1",
    "Alternate Image 2",
    "Alternate Image 3",
    "Alternate Image 4",
    "Actual Image (Yes/No)",

    # Documents & URLs
    "MFR URL",
    "Ref URL 1",
    "Ref URL 2",
    "Ref URL 3",
    "Ref URL 4",
    "Ref URL 5",
    "SDS",
    "SDS_1",
    "Warranty Information",
    "Catalog",
    "Specification Sheet",
    "Instruction/Installation Manual",
    "Service Manual",
    "Owners/User Manual",
    "Line Drawing",
    "MTR",
    "RoHS",
    "Full Engineering Drawing",
    "Energy Star Guide",
    "Technical Bulletin",
    "Submittal",
    "Compatibility Chart",
    "Size Chart",
    "Product Label/Insert",
    "Video Link",
    "Video Link 1",

    # Other metadata
    "Warranty",
    "Country Of Origin",
    "Discontinued",
]


# =========================================================================
# FULL OUTPUT COLUMN ORDER (matches expected_output_delivery_format.csv)
# =========================================================================
OUTPUT_COLUMN_ORDER = [
    "MFR URL", "Ref URL 1", "Ref URL 2", "Ref URL 3", "Ref URL 4",
    "Ref URL 5", "PART_NUMBER", "Dept", "Class", "Fine",
    "SKU - MY_PART_NUMBER", "Mfg_Part_Num", "Part_Desc", "E1_Brand",
    "Unilog_Brand", "DIB_Brand", "Part_Manuf", "MANUFACTURER_NAME",
    "BRAND_NAME", "TRADE_NAME", "MANUFACTURER_PART_NUMBER",
    "ALTERNATE_PART_NUMBER", "Classpath", "MOBILE_DESC", "INVOICE_DESC",
    "SHORT_DESC", "LONG_DESC1", "RETAIL_DESC", "MARKETING_DESCRIPTION",
    *[f"ITEM_FEATURES_{i}" for i in range(1, 21)],
    "With", "Standard/Approvals", "Prop 65", "Application", "Includes",
    "Product Name",
    # 50 attribute triplets
    *[col for i in range(1, 51)
      for col in (f"ATTRIBUTE_LABEL {i}", f"ATTRIBUTE_VALUE {i}",
                  f"ATTRIBUTE_UOM {i}")],
    "UPC", "EAN", "GTIN", "UNSPSC", "Warranty", "List Price",
    "Selling Qty", "Selling UOM", "Standard Packaging Information",
    "LENGTH", "LENGTH_UOM", "HEIGHT", "HEIGHT_UOM", "WIDTH", "WIDTH_UOM",
    "WEIGHT", "WEIGHT_UOM", "VOLUME", "VOLUME_UOM",
    "Product Image", "Alternate Image 1", "Alternate Image 2",
    "Alternate Image 3", "Alternate Image 4",
    "SDS", "SDS_1", "Warranty Information", "Catalog",
    "Specification Sheet", "Instruction/Installation Manual",
    "Service Manual", "Owners/User Manual", "Line Drawing", "MTR",
    "RoHS", "Full Engineering Drawing", "Energy Star Guide",
    "Technical Bulletin", "Submittal", "Compatibility Chart",
    "Size Chart", "Product Label/Insert", "Video Link", "Video Link 1",
    "Country Of Origin", "Discontinued", "Actual Image (Yes/No)",
]


# =========================================================================
# HELPERS
# =========================================================================

def all_enrichment_columns() -> list[str]:
    """All columns the pipeline is responsible for generating (not passthrough)."""
    return CLEAN_COLUMNS + DETERMINISTIC_COLUMNS + AI_ENRICHMENT_COLUMNS + EXTERNAL_DATA_COLUMNS


def columns_for_phase(phase: int) -> list[str]:
    """
    Return the columns that should be populated by a given pipeline phase.

    Phase 1 (deterministic): PASSTHROUGH + CLEAN + DETERMINISTIC
    Phase 2 (AI):            AI_ENRICHMENT
    Phase 3 (external):      EXTERNAL_DATA (when reference files are added)
    """
    if phase == 1:
        return PASSTHROUGH_COLUMNS + CLEAN_COLUMNS + DETERMINISTIC_COLUMNS
    elif phase == 2:
        return AI_ENRICHMENT_COLUMNS
    elif phase == 3:
        return EXTERNAL_DATA_COLUMNS
    else:
        raise ValueError(f"Unknown phase: {phase}")


def validate_output_columns(columns: list[str]) -> dict:
    """
    Check a list of output columns against the expected schema.
    Returns dict with 'missing' and 'extra' lists.
    """
    expected = set(OUTPUT_COLUMN_ORDER)
    actual = set(columns)
    return {
        "missing": sorted(expected - actual),
        "extra": sorted(actual - expected),
    }
